name: NiftyWarp
main: net.niftymonkey.niftywarp.NiftyWarp
version: 0.1
description: >
             A Nifty Warp plugin that allows private, public listed, and public unlisted warps
commands:
   warp:
      description: Warps you to a named warp location
      usage: |
           /<command> <name>
   addwarp:
      description: Sets a named warp to your current location
      usage: |
           /<command> <name>
   listwarps:
      description: Lists all of the warps available to you
      usage: |
           /<command>
